#!/bin/sh

LC_ALL=C
export LC_ALL

case "${#}" in
  0|1)
    cat >&2 <<'EOF'
usage: git tsr <object> <server>...
EOF
    exit 128
    ;;
  *)
    :
    ;;
esac

hash=`git rev-parse --verify "${1}"`
case "${?}" in
  0)
    :
    ;;
  *)
    exit 1
    ;;
esac

shift

for server do

  url=`git config --get "tsr.${server}"`
  case "${?}" in
    0)
      :
      ;;
    *)
      cat >&2 <<EOF
warning: unknown server: ${server}
EOF
      continue
      ;;
  esac

  if openssl ts -query -sha1 -digest "${hash}" -cert >.git-tsr.tsq; then
    :
  else
    rm -f .git-tsr.tsq
    continue
  fi

done

exit 0

#
# The authors of this file have waived all copyright and
# related or neighboring rights to the extent permitted by
# law as described by the CC0 1.0 Universal Public Domain
# Dedication. You should have received a copy of the full
# dedication along with this file, typically as a file
# named <CC0-1.0.txt>. If not, it may be available at
# <https://creativecommons.org/publicdomain/zero/1.0/>.
#
