#!/bin/sh

#
# With LC_ALL=C, locale-aware programs use the C locale instead of the
# current locale. This is generally the best approach for code that is
# not deliberately designed to work in other locales. The C locale has
# predictable behavior and is compatible with UTF-8. Other locales may
# have surprising behavior. This affects many important programs, like
# awk, grep, sed, and this shell instance itself. For more information,
# see the C standard, the POSIX standard, and the GNU C Library manual.
#

LC_ALL=C
export LC_ALL

case "${#}" in
  0|1)
    cat >&2 <<'EOF'
usage: git tsr <object> <server>...
EOF
    exit 128
    ;;
esac

hash=`git rev-parse --verify "${1}"`
case "${?}" in
  0)
    :
    ;;
  *)
    exit 1
    ;;
esac

shift

skipped_one_or_more_servers=0

for server do

  url=`git config --get "tsr.${server}"`
  case "${?}" in
    0)
      :
      ;;
    *)
      cat >&2 <<EOF
warning: skipping unknown server '${server}'
EOF
      skipped_one_or_more_servers=1
      continue
      ;;
  esac

  if openssl ts -query -sha1 -digest "${hash}" -cert >.git-tsr.tsq; then
    :
  else
    rm -f .git-tsr.tsq
    cat >&2 <<EOF
warning: skipping server '${server}' due to errors
EOF
    skipped_one_or_more_servers=1
    continue
  fi

  if curl --header 'Content-Type: application/timestamp-query' \
          --data-binary @.git-tsr.tsq --url "${url}" \
          --silent --show-error >.git-tsr.tsr; then
    :
  else
    rm -f .git-tsr.tsq
    rm -f .git-tsr.tsr
    cat >&2 <<EOF
warning: skipping server '${server}' due to errors
EOF
    skipped_one_or_more_servers=1
    continue
  fi

  rm -f .git-tsr.tsq

  if openssl ts -reply -in .git-tsr.tsr -text >.git-tsr.txt; then
    :
  else
    rm -f .git-tsr.tsr
    rm -f .git-tsr.txt
    cat >&2 <<EOF
warning: skipping server '${server}' due to errors
EOF
    skipped_one_or_more_servers=1
    continue
  fi

  date=`awk '
/Time stamp:/ {
  x["Jan"] = "01"
  x["Feb"] = "02"
  x["Mar"] = "03"
  x["Apr"] = "04"
  x["May"] = "05"
  x["Jun"] = "06"
  x["Jul"] = "07"
  x["Aug"] = "08"
  x["Sep"] = "09"
  x["Oct"] = "10"
  x["Nov"] = "11"
  x["Dec"] = "12"
  gsub(/:/, "")
  printf "%s%s%.2dT%sZ\n", $6, x[$3], $4, $5
}
' .git-tsr.txt`
  case "${?}" in
    0)
      :
      ;;
    *)
      rm -f .git-tsr.tsr
      rm -f .git-tsr.txt
      cat >&2 <<EOF
warning: skipping server '${server}' due to errors
EOF
      skipped_one_or_more_servers=1
      continue
      ;;
  esac

  rm -f .git-tsr.txt

  target="${date}-${hash}-${server}.tsr"
  if cat .git-tsr.tsr >"${target}"; then
    :
  else
    rm -f .git-tsr.tsr
    if rm -f "${target}"; then
      :
    else
      cat >&2 <<EOF
warning: unable to remove possibly corrupt file '${target}'
EOF
    fi
    cat >&2 <<EOF
warning: skipping server '${server}' due to errors
EOF
    skipped_one_or_more_servers=1
    continue
  fi

  rm -f .git-tsr.tsr

  sleep 10

done

exit "${skipped_one_or_more_servers}"

#
# The authors of this file have waived all copyright and
# related or neighboring rights to the extent permitted by
# law as described by the CC0 1.0 Universal Public Domain
# Dedication. You should have received a copy of the full
# dedication along with this file, typically as a file
# named <CC0-1.0.txt>. If not, it may be available at
# <https://creativecommons.org/publicdomain/zero/1.0/>.
#
